In [4]:
import numpy as np
list1 = [45,56,66.7,78]
myarray=np.array(list1)
print(myarray)
print(type(myarray))

[45.  56.  66.7 78. ]
<class 'numpy.ndarray'>


In [5]:
list2 = [[1,3,6],[6,7,8],[7,5,4]]
array1 = np.array(list2)
print(array1)

[[1 3 6]
 [6 7 8]
 [7 5 4]]


In [8]:
import numpy as abc
array1 = abc.arange(25,101)
print(array1)

[ 25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42
  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60
  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
  97  98  99 100]


In [9]:
import numpy as np
array1 = np.arange(11,19).reshape((2,4))
print(array1)

[[11 12 13 14]
 [15 16 17 18]]
